title: Philipp Do&#x11F;an
url: ""
baseurl: ""

markdown: kramdown
ins_logo: "./dancing-tachikoma.gif"

tracking_id: #

footer: no
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "index"
 - name: "Contact"
   link: "contact"
