title: Philipp Do&#x11F;an
url: ""
baseurl: ""

markdown: kramdown
ins_logo: "./tachikoma-clip.jpg"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana/researcher"
footer_text: Created with Jekyll & Researcher theme

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "index"
 - name: "Contact"
   link: "contact"
