title: Philipp Do&#x11F;an
url: ""
baseurl: ""

markdown: kramdown
ins_logo: "./tachikoma-clip.png"

tracking_id: #

footer: yes
footer_url: "https://twitter.com/based_tachikoma"
footer_text: <img src="twitter2.jpg">

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "index"
 - name: "Contact"
   link: "contact"
